service: inputform-backend

provider:
  name: aws
  runtime: java8
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  artifact: target/scala-2.12/inputform-backend.jar

functions:
  create:
    handler: inputform.backend.service.create.CreateItemService
    events:
      - http:
          path: form
          method: post
          cors: true
  get:
    handler: inputform.backend.service.get.GetItemService
    events:
      - http:
          path: form/{id}
          method: get
          cors: true
  list:
    handler: inputform.backend.service.list.ListItemService
    events:
      - http:
          path: form
          method: get
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}